# Saket Vats

In [4]:
1+3

4

In [5]:
11+12

23

In [6]:
import numpy as np

In [8]:
a = np.arange(5)

In [11]:
print(a<=3)

[ True  True  True  True False]


In [12]:
import pandas as pd
import numpy as np

s = pd.Series(['a', 3, np.nan, 1, np.nan])

print(s.notnull().sum())

3


In [14]:
import pandas as pd
import numpy as np

s = pd.Series([0,np.nan, 1, 2, np.nan, 3])
s = s.fillna(method='ffill')

print(s)

0    0.0
1    0.0
2    1.0
3    2.0
4    2.0
5    3.0
dtype: float64


In [16]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 10))

[[10 10 10 10 10]
 [10 10 10 10 10]]


In [23]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=0)
print(b)

[ 6  7  8  9 10]


In [35]:
A = np.array([0,1,2,3,4,5,6,7,8])
B = np.reshape(A, (-1, 3))
print(np.mean(B))

4.0
